[General]
# Global defaults (can be overridden per artist)
# Options: audio, video
media_type = video
# Audio options: mp3, m4a, wav, etc.
# Video options: webm, mp4, mkv, etc.
# Default format for audio is mp3, for video is mp4
format = mp4
# Audio quality: 0 (best) to 9 (worst), or specific bitrate like 320K
# Video quality: 1080p, 720p, 480p, etc.
# Default audio is best (0), default video is 720p
quality = 480

# Maximum results per search query (increase for more coverage, default = 20)
max_results = 5

# FFmpeg location (leave empty to use system PATH)
# Example: C:\Path\To\ffmpeg\bin
ffmpeg_location = C:\Users\John Tan\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-8.0.1-full_build\bin



; [Artist:Ayumi Hamasaki]
; # If no keywords provided, defaults to "{SectionName} official"
; keywords = Ayumi Hamasaki official audio, 浜崎あゆみ official
; output_folder = Ayumi Hamasaki
; # Override to specific settings if needed
; media_type = audio
; format = mp3
; quality = 0

; [Artist:Bruno Mars]
; media_type = video
; format = mp4
; quality = 1080p
; output_folder = Bruno Mars

; [Artist:Taylor Swift]
; # Uses global defaults (audio/webm/best) if not specified
; output_folder = Taylor Swift
; media_type = audio
; format = mp3
; quality = 320K
