/**
 * PDF Generator for MapleWay Extension
 * Uses html2pdf.js to generate PDF from DOM elements
 */

const PDFGenerator = {
    /**
     * Generate PDF from the current results
     * @param {string} streamName - The name of the selected stream
     */
    generate: function (streamName) {
        return new Promise((resolve, reject) => {
            console.log('[PDF Debug] Starting generation for:', streamName);

            // Elements
            const resultsEl = document.getElementById('results');
            const mainContainer = document.querySelector('.container');

            if (!resultsEl || resultsEl.classList.contains('hidden')) {
                console.error('[PDF Debug] No results element found or it is hidden');
                reject(new Error('No results to print'));
                return;
            }

            // SNAPSHOT: Capture current styles to restore later
            const originalBodyStyle = {
                overflow: document.body.style.overflow,
                height: document.body.style.height
            };
            const originalHtmlStyle = {
                overflow: document.documentElement.style.overflow,
                height: document.documentElement.style.height
            };

            // PREPARE ENVIRONMENT:
            // Force body and html to allow full expansion. 
            // This is critical because extensions have fixed popup sizes.
            document.documentElement.style.cssText = "height: auto !important; overflow: visible !important;";
            document.body.style.cssText = "height: auto !important; overflow: visible !important;";

            // Create a dedicated container for printing
            const printContainer = document.createElement('div');
            printContainer.className = 'print-container';
            printContainer.id = 'temp-print-container';

            // Styling: 
            Object.assign(printContainer.style, {
                width: '100%',
                maxWidth: '800px',
                // Restore negative margin to pull content to the top
                // Adjusted to -0px (was -40px) to prevent cutting off the title
                margin: '-0px auto 0',
                background: 'white',
                // Large bottom padding to prevent bottom clipping
                padding: '0 20px 100px 20px',
                boxSizing: 'border-box',
                fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
                color: '#333',
                display: 'block',
                position: 'relative'
            });

            // Add Header
            const header = document.createElement('div');
            header.innerHTML = `
                <div style="text-align: center; margin-bottom: 20px; border-bottom: 2px solid #0077b6; padding-bottom: 10px;">
                    <h1 style="color: #0077b6; margin: 0; font-size: 24px;">${streamName}</h1>
                    <p style="color: #666; margin: 5px 0 0 0; font-size: 14px;">Assessment Summary</p>
                    <p style="color: #999; margin: 2px 0 0 0; font-size: 12px;">Generated by MapleWay</p>
                </div>
            `;
            printContainer.appendChild(header);

            // Clone content
            const contentClone = resultsEl.cloneNode(true);

            // Cleanup Clone:
            contentClone.classList.remove('hidden');
            contentClone.style.maxHeight = 'none';
            contentClone.style.overflow = 'visible';

            // Remove the Download UI section from the PDF
            const downloadSection = contentClone.querySelector('#download-section');
            if (downloadSection) {
                downloadSection.remove();
            }

            printContainer.appendChild(contentClone);

            // SWAP: Hide main container, Show print container
            if (mainContainer) mainContainer.style.display = 'none';
            document.body.appendChild(printContainer);

            // Generate Timestamp
            const now = new Date();
            const dateStr = now.toISOString().split('T')[0]; // YYYY-MM-DD
            const timeStr = now.toTimeString().split(' ')[0].replace(/:/g, '_'); // HH_MM_SS
            const timestamp = `${dateStr}_${timeStr}`;

            // Options
            const opt = {
                // Top margin 0 to utilize the negative margin positioning
                margin: [0, 0.3, 0.3, 0.3],
                filename: `${streamName.replace(/[^a-zA-Z0-9]/g, '_')}_Summary-${timestamp}.pdf`,
                image: { type: 'jpeg', quality: 0.98 },
                html2canvas: {
                    scale: 2,
                    useCORS: true,
                    logging: true,
                    windowWidth: 800,
                    // CRITICAL: Set a large windowHeight to force capturing content beyond the visible viewport of the popup
                    windowHeight: 3000,
                    scrollY: 0
                },
                jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
            };

            // Generate
            html2pdf().set(opt).from(printContainer).save()
                .then(() => {
                    console.log('[PDF Debug] Save successful');
                    resolve();
                })
                .catch(err => {
                    console.error('[PDF Debug] PDF Generation failed:', err);
                    reject(err);
                })
                .finally(() => {
                    // RESTORE UI
                    console.log('[PDF Debug] Restoring UI and Styles');
                    if (document.body.contains(printContainer)) {
                        document.body.removeChild(printContainer);
                    }
                    if (mainContainer) mainContainer.style.display = 'block';

                    // RESTORE STYLES
                    document.body.style.overflow = originalBodyStyle.overflow;
                    document.body.style.height = originalBodyStyle.height;
                    document.documentElement.style.overflow = originalHtmlStyle.overflow;
                    document.documentElement.style.height = originalHtmlStyle.height;
                });
        });
    }
};
